---
title: "R Notebook"
output: html_notebook
---

```{r}
# clean up R environment
rm(list = ls())

library(dplyr)
library(tidyr)
library(stringr)
library(mosaic)
library(plyr)
library(ggplot2)
library(rvest)
library(reshape2)
library(readxl)
library(rpart)
library(partykit)
library(mclust)
library(tibble)
library(readr)
library(viridis)
library(RColorBrewer)
library(maps)
library(maptools)
library(mapdata)
library(ggthemes)
library(cluster)
library(fpca)
library(doParallel)
```

```{r}
#using multiple cores
myCluster <- makeCluster(detectCores() - 1, type = "FORK")

# options
# display as decimal, not scientific notation
options(scipen = 999)

# data for 2013 - 2016
county_poverty <- read.csv(file = 'county_poverty_hist.csv', header = TRUE, sep = ',')
county_poverty$geo_sumlevel <- gsub('[[:punct:]]\\s', '', str_extract(county_poverty$geo_name, '\\,\\s[A-Z]{2}'))
county_poverty$geo_name <- gsub('\\,\\s[A-Z]{2}', '', county_poverty$geo_name)
county_poverty <- county_poverty[-3]

# naming scheme:
# pYEAR = number of people in poverty, for the given year
# prYEAR = poverty rate, for the given year
# popYEAR = total population, for the given year
names(county_poverty) <- c('county', 'state', 
                           'p2013', 'p2014', 'p2015', 
                           'pr2013', 'pr2014', 'pr2015', 
                           'pr2016', 'p2016', 'pop2013', 
                           'pop2014', 'pop2015', 'pop2016')

county_poverty <- county_poverty %>% 
  na.omit() %>%
  select(sort(current_vars()))

# remove Puerto Rico
county_poverty <- county_poverty %>% 
  filter(state != 'PR')

county_poverty <- county_poverty %>% 
  select(sort(current_vars()))
```

```{r}
# economic/unemployment data
# https://apps.bea.gov/regional/
ec <- read.csv('CAINC4__ALL_STATES_1969_2017.csv', header = TRUE, sep = ',')
ec <- ec[, c('GeoFIPS', 'GeoName', 'Description', 'X2013', 'X2014', 'X2015', 'X2016')]
ec$Description <- gsub('[[:punct:]]', '', ec$Description) %>% 
  trimws()

# keep 'Per capita personal income (dollars) 4/', 'Total employment', 'Farm proprietors' income', 'Nonfarm proprietors' income'
# clean data
ec <- ec %>% 
  filter(ec$Description == 'Per capita personal income dollars 4' | 
                      ec$Description == 'Total employment' | 
                      ec$Description == 'Farm proprietors income' | 
                      ec$Description == 'Nonfarm proprietors income')
ec$Description[ec$Description == 'Per capita personal income dollars 4'] <- 'income'
ec$Description[ec$Description == 'Total employment'] <- 'empl_count'
ec$Description[ec$Description == 'Farm proprietors income'] <- 'farm_income'
ec$Description[ec$Description == 'Nonfarm proprietors income'] <- 'nonfarm_income'

ec <- dcast(melt(ec, 
                 id.vars = c('GeoFIPS', 'GeoName', 'Description'), 
                 measure.vars = c('X2013', 'X2014', 'X2015', 'X2016')), 
            GeoFIPS + GeoName + variable ~ Description) %>% 
  mutate(variable = gsub('X', '', variable))

ec[, 1:2] <- lapply(ec[, 1:2], as.character)
ec[, c(1, 3:7)] <- lapply(ec[, c(1, 3:7)], as.numeric)
ec$p_farm_income <- ec$farm_income / ec$nonfarm_income
ec[is.na(ec)] <- 0

# combine economic data with land area
area <- read_excel('LND01.xls')[,c(2,4)]
names(area) <- c('GeoFIPS', 'area')
area <- lapply(area, as.numeric)
ec <- merge(ec, area, by = 'GeoFIPS')

# state data
## COMBINE WITH 'STATE_DATA' DATA FRAME
state_ec <- ec[(ec$GeoFIPS %% 1000 == 0), ]
state_ec <- state_ec %>% 
  filter(GeoFIPS < 90000 & GeoFIPS != 0)
state_ec <- subset(state_ec, select = -c(GeoFIPS))
names(state_ec) <- c('state', 'year', 
                     'empl_count', 'farm_income', 
                     'income', 'nonfarm_income', 
                     'p_farm_income', 'area')
```

```{r}
# create tall data set
cp1 <- gather(county_poverty[c(1:5, 14)], year, poverty_count, p2013:p2016, factor_key = TRUE) %>% 
  mutate(year = str_extract(year, '\\d{4}'))
cp2 <- gather(county_poverty[c(1, 6:9, 14)], year, total_count, pop2013:pop2016, factor_key = TRUE) %>% 
  mutate(year = str_extract(year, '\\d{4}'))
cp <- merge(cp1, cp2, by = c('county', 'state', 'year')) %>% 
  mutate(poverty_rate = poverty_count / total_count,
         year = year %>% as.numeric())

cp$county <- gsub('\\sCounty', '', cp$county)
cp$county <- gsub('\\sParish', '', cp$county)
cp$county <- gsub('\\scity', '\\sCity', cp$county)
cp$county <- gsub('[[:punct:]]', '', cp$county)
cp$county <- cp$county %>% 
  trimws()

# county data
county_ec <- ec[!(ec$GeoFIPS %% 1000 == 0), ]
county_ec <- subset(county_ec, select = -c(GeoFIPS))
county_ec$state <- gsub('[[:punct:]]\\s', '', str_extract(county_ec$GeoName, '\\,\\s[A-Z]{2}'))
county_ec$GeoName <- gsub('\\,\\s[A-Z]{2}', '', county_ec$GeoName)
names(county_ec) <- c('county', 'year', 'empl_count', 
                      'farm_income', 'income', 'nonfarm_income', 
                      'p_farm_income', 'area', 'state')

county_ec$county <- gsub('[[:punct:]]', '', county_ec$county)
county_ec$county <- gsub('\\sIndependent\\sCity', '\\sCity', county_ec$county)
county_ec$county <- gsub('\\sStaunton\\sWaynesboro', '', county_ec$county)
```

```{r}
# manual fix for counties with area = 0
# scrape areas from Wikipedia, as Census data was inadequate
zeroarea <- county_ec[which(county_ec$area == 0), -c(2:7)] %>% 
  unique()
zeroarea$wiki_link <- gsub(' City and Borough', '', zeroarea$county)
zeroarea$wiki_link <- gsub(' Municipality', '', zeroarea$wiki_link)
zeroarea$wiki_link <- gsub('[A-Z]{2}', '', 
                           paste('https://en.wikipedia.org/wiki/', 
                                 gsub('\\s', '_', zeroarea$wiki_link), ',_', 
                                 gsub('AK', 'Alaska', zeroarea$state), 
                                 gsub('CO', 'Colorado', zeroarea$state), 
                                 sep = ''))

for(i in 1:nrow(zeroarea)) {
  zeroarea$area[i] <- gsub(',', '', read_html(zeroarea$wiki_link[i]) %>% 
                        html_nodes(xpath = '//th[contains(., "Area")]//parent::tr/following-sibling::tr[1]/td') %>% 
                        html_text() %>% 
                        str_extract('[\\d\\.,]+'))[1] %>% 
  as.numeric()
  county_ec$area[which(county_ec$county == zeroarea$county[i])] <- zeroarea$area[which(zeroarea$county == zeroarea$county[i])]
}
```

```{r}
county_data <- merge(cp, county_ec, 
                     by = c('county', 'state', 'year')) %>% 
  mutate(empl_rate = empl_count / total_count, 
         pop_dens = total_count / area)

# 'county_data' to wide
st <- list()
for (i in 2013:2016) {
  df <- county_data %>% 
    filter(year == i)
  df <- df[, -3]
  df_names <- names(df)
  df_names[3] <- paste('p', i %>% as.character(), sep = '')
  df_names[4] <- paste('pop', i %>% as.character(), sep = '')
  df_names[5] <- paste('pr', i %>% as.character(), sep = '')
  df_names[6] <- paste('ec', i %>% as.character(), sep = '')
  df_names[7] <- paste('f_inc', i %>% as.character(), sep = '')
  df_names[8] <- paste('inc', i %>% as.character(), sep = '')
  df_names[9] <- paste('nf_inc', i %>% as.character(), sep = '')
  df_names[10] <- paste('pf_inc', i %>% as.character(), sep = '')
  df_names[12] <- paste('er', i %>% as.character(), sep = '')
  df_names[13] <- paste('pop_dens', i %>% as.character(), sep = '')
  names(df) <- df_names
  st[[i - 2012]] <- df
}

county_data_wide <- merge(st[[1]], st[[2]], 
                          by = c('state', 'county', 'area'))
county_data_wide <- merge(county_data_wide, st[[3]], 
                          by = c('state', 'county', 'area'))
county_data_wide <- merge(county_data_wide, st[[4]], 
                          by = c('state', 'county', 'area'))
```

```{r}
# data set of poverty, by state
state_poverty <- table(county_data_wide$state) %>% 
  data.frame()
names(state_poverty) <- c('state', 'n_counties')

# 51 = number of states, including Washington D.C.

# create a data table of summary stats per state
sp <- list()
for(i in 1:51) {
  state_stats <- data.frame(summary(county_data_wide[which(county_data_wide$state == state_poverty$state[i]), ]))[13:258, 2:3] %>% 
  mutate(stat = gsub('\\s*\\:', '', 
                     str_extract(Freq, '.*\\:')), 
         Freq = gsub(':', '', 
                     str_extract(Freq, '\\:.+')) %>% 
           as.numeric()) %>% 
  reshape(idvar = 'Var2', timevar = 'stat', direction = 'wide') %>%
  mutate(Year = str_extract(Var2, '\\d{4}'), 
         Var2 = str_extract(Var2, '[a-z_]{1,7}'), 
         state = state_poverty$state[i])
  sp[[i]] <- state_stats
}

# clean data, rename variables and reorganize column order
state_poverty <- merge(state_poverty, do.call(rbind, sp), by = 'state') %>% 
  select(sort(current_vars()))
state_poverty <- state_poverty[, c(8, 10, 7, 9, 1:6)]
state_poverty$Var2[state_poverty$Var2 == 'p'] <- 'poverty_count'
state_poverty$Var2[state_poverty$Var2 == 'pr'] <- 'poverty_rate'
state_poverty$Var2[state_poverty$Var2 == 'pop'] <- 'total_count'
state_poverty$Var2[state_poverty$Var2 == 'ec'] <- 'empl_count'
state_poverty$Var2[state_poverty$Var2 == 'f_inc'] <- 'farm_income'
state_poverty$Var2[state_poverty$Var2 == 'inc'] <- 'income'
state_poverty$Var2[state_poverty$Var2 == 'f_inc'] <- 'farm_income'
state_poverty$Var2[state_poverty$Var2 == 'nf_inc'] <- 'nonfarm_income'
state_poverty$Var2[state_poverty$Var2 == 'pf_inc'] <- 'p_farm_income'
state_poverty$Var2[state_poverty$Var2 == 'er'] <- 'empl_rate'
state_poverty$Var2[state_poverty$Var2 == 'area'] <- 'area'
state_poverty$Var2[state_poverty$Var2 == 'pop_den'] <- 'pop_dens'
names(state_poverty) <- c('state', 'year', 'n_counties', 'countystat', '1st_quantile', '3rd_quantile', 'max', 'mean', 'median', 'minimum')

# replace NAs for 'year'
for(i in 1:nrow(state_poverty)) {
  if(state_poverty$year[i] %>% is.na) {
    state_poverty$year[i] <- state_poverty$year[i + 1]
  }
}

# create variables measuring the standard deviation and variance of county stats, per year
state_variance <- c()
state_sd <- c()
for(i in 1:nrow(state_poverty)) {
  state_variance[i] <- county_data %>% 
    filter(state == state_poverty$state[i] & year == state_poverty$year[i]) %>% 
    select(state_poverty$countystat[i]) %>% 
    var()
  state_sd[i] <- sapply(county_data %>% 
                          filter(state == state_poverty$state[i] & year == state_poverty$year[i]) %>% 
                          select(state_poverty$countystat[i]), 
                        sd)[[1]][1]
}

state_poverty$var <- state_variance
state_poverty$sd <- state_sd
state_poverty[is.na(state_poverty)] <- 0

# merge state stats with statistics on total state population ('state_ec'), total state poverty count, and overall state poverty rate (aggregating 'cp')
# change 'state_ec' names from full words to 2-letter abbreviations
for(i in 1:nrow(state_ec)) {
  if(state_ec$state[i] == 'District of Columbia') {
    state_ec$state[i] <- 'DC'
  } else {
    state_ec$state[i] <- state.abb[grep(state_ec$state[i], state.name)]
  }
}

state_ec <- merge(state_ec, 
                  merge(aggregate(poverty_count ~ state + year, cp, sum), 
                        aggregate(total_count ~ state + year, cp, sum), 
                        by = c('state', 'year')), 
                  by = c('state', 'year')) %>% 
  mutate(poverty_rate = poverty_count / total_count, 
         empl_rate = empl_count / total_count)

state_ec <- merge(state_poverty, state_ec, by = c('state', 'year'))

# rename state-wide variables for clarity
names(state_ec) <- c('state', 'year', 'n_counties', 
                     'countystat', '1st_quantile', '3rd_quantile', 
                     'max', 'mean', 'median', 
                     'minimum', 'var', 'sd', 
                     'state_empl_count', 'state_farm_income', 'state_avg_income', 
                     'state_nonfarm_income', 'state_p_farm_income', 'state_area', 
                     'state_poverty_count', 'state_total_count', 'state_poverty_rate', 
                     'state_empl_rate')
```


```{r}
# per-state crime data, merge with 'state_data'
state_crime <- read.csv(file = 'estimated_crimes.csv', header = TRUE, sep = ',')
state_data <- merge(state_ec, state_crime[, -c(2, 4:5, 15)], 
                    by.x = c('year', 'state'), by.y = c('year', 'state_abbr')) %>% 
  mutate(state_vcrime_rate = violent_crime / state_total_count,
         state_pcrime_rate = property_crime / state_total_count,
         state_pop_dens = state_total_count / state_area)
state_data <- state_data[, c(1:3, 20, 18, 34, 15, 4:12, 17, 13, 22, 19, 21, 23, 32, 28, 33)]
state_data$year <- state_data$year %>% as.numeric()

# explain 'state_data' variables below
# year: 2013-2016
# state: state, within the United States
# n_counties: number of counties in this state
# state_total_count: state population
# countystat: type of statistic, measured within counties of each state
## empl_count: number of employed individuals working per county
## farm_income: amount of income from farming per county
## nonfarm_income: amount of income from non-farming industries per county
## p_farm_income: ratio of 'farm_income' to 'nonfarm_income' per county, can be negative, indicator of how rural counties are
## empl_rate: ratio of employed individuals working per county, can be >1
## poverty_rate: percentage of individuals in poverty per county
## poverty_count: number of individuals in poverty per county
## total_count: population per county
# 1st_quantile:sd: statistics on counties, per state and year
# state_avg_income: average income per individual per state and year
# state_p_farm_income: ratio of 'farm_income' to 'nonfarm_income' per state and year, can be negative, indicator of how rural counties are
# state_poverty_count: number of individuals in poverty per state and year
# state_poverty_rate: percentage of individuals in poverty per state and year
# state_empl_count: number of employed individuals working per state and year
# state_empl_rate: ratio of employed individuals working per state and year
# violent_crime: number of violent crimes per state and year
# state_vcrime_rate: rate of violent crimes per state and year
# property_crime: number of property crimes per state and year
# state_pcrime_rate: rate of property crimes per state and year

# save 'state_data' as .csv file
write.csv(state_data, file = 'state_data.csv')
```

```{r}
# various regressions
lm(state_vcrime_rate ~ state + year + var, 
   data = state_data %>% filter(countystat == 'poverty_rate')) %>% 
  msummary()
lm(state_vcrime_rate ~ state + year + var, 
   data = state_data %>% filter(countystat == 'pop_dens')) %>% 
  msummary()
lm(state_vcrime_rate ~ state + year + mean, 
   data = state_data %>% filter(countystat == 'p_farm_income')) %>% 
  msummary()
lm(state_vcrime_rate ~ state + year + var, 
   data = state_data %>% filter(countystat == 'empl_rate')) %>% 
  msummary()
lm(state_vcrime_rate ~ state + year + mean, 
   data = state_data %>% filter(countystat == 'income')) %>% 
    msummary()
```

```{r}
state_data %>% 
  filter(countystat == 'poverty_rate') %>% 
  select(var) %>% 
  unique() %>% 
  ggplot(aes(x = var)) + 
  geom_density()
```

```{r}
# decision trees
rpart(state_vcrime_rate ~ state + year, 
      data = state_data)
rpart(state_vcrime_rate ~ var, 
      data = state_data %>% filter(countystat == 'poverty_rate'))
rpart(state_vcrime_rate ~ ., 
      data = state_data)
rpart(state_vcrime_rate ~ state + var, 
      data = state_data %>% filter(countystat == 'pop_dens'))
```

```{r}
plot(as.party(rpart(state_vcrime_rate ~ ., data = state_data)))
```

```{r}
plot(as.party(rpart(state_vcrime_rate ~ var + state_avg_income, data = state_data %>% filter(countystat == 'income'))))
```

```{r}
state_data_pca_df <- state_data[,c(1:7, 17:25)] %>% 
  unique()
rownames(state_data_pca_df) <- paste(state_data_pca_df$state, state_data_pca_df$year, sep = '')

state_data_pca <- state_data_pca_df[, -2] %>% 
  prcomp(scale = TRUE)
-1 * state_data_pca$rotation[, 1:4] %>% 
  round(3)
```

```{r}
summary(state_data_pca)
```

```{r}
data.frame(sd = state_data_pca$sdev) %>% 
  rownames_to_column() %>% 
  mutate(rowname = parse_number(rowname), 
         totalVar = sum(state_data_pca$sdev^2), 
         pve = 100 * sd^2 / totalVar, 
         cusum = cumsum(pve)) %>% 
  ggplot(aes(x = rowname, y = pve)) + 
  geom_line()
```

```{r}
data.frame(sd = state_data_pca$sdev) %>% 
  rownames_to_column() %>% 
  mutate(rowname = parse_number(rowname), 
         totalVar = sum(state_data_pca$sdev^2), 
         pve = 100 * sd^2 / totalVar, 
         cusum = cumsum(pve)) %>% 
  ggplot(aes(x = rowname, y = cusum)) + 
  geom_line()
```

```{r}
pca_data <- state_data_pca$x %>% 
  data.frame() %>% 
  rownames_to_column() %>% 
  mutate(year = str_extract(rowname, '\\d+') %>% as.numeric(), 
         rowname = gsub('\\d{4}', '', rowname))

pca_data %>% 
  ggplot(aes(x = -PC1, y = -PC2, 
             colour = year %>% as.factor())) + 
  geom_text(aes(label = rowname), size = 3)
```

```{r}
# averaged values, per year
aggregate(pca_data, by = list(pca_data$rowname), FUN = mean) %>% 
  ggplot(aes(x = -PC1, y = -PC2)) + 
  geom_text(aes(label = Group.1), size = 3)
```

```{r}
# averaged values, per year
pca_data_alt <- aggregate(pca_data, by = list(pca_data$rowname), FUN = mean)
rownames(pca_data_alt) <- pca_data_alt$Group.1
pca_data_alt <- pca_data_alt[, 3:17]
pca_data_alt %>% 
  dist() %>% 
  hclust() %>% 
  plot(cex = 0.8)
```

```{r fig.width = 16, fig.height = 6}
pca_data2 <- state_data_pca$x %>% 
  data.frame() %>% 
  rownames_to_column() 

pca_data2 %>% 
  dist() %>% 
  hclust() %>% 
  plot(cex = 0.8, labels = pca_data2$rowname)
```

```{r}
# visualization
df <- aggregate(state_poverty_rate ~ state, data = state_data, mean)
df <- filter(df, 
             state != "DC") 
mycolors_True <- brewer.pal(9, "GnBu")
states <- tolower(rownames(USArrests))
map_50S <- map_data("state")

ggplot(data = df,
       aes(fill = state_poverty_rate)) +
  labs(x = "Longitude", y = "Latitude", title = "Average Poverty Rate in States") +
  geom_map(aes(map_id = states), map = map_50S) +
  expand_limits(x = map_50S$long, y = map_50S$lat) +
  theme_bw() + 
  scale_fill_gradientn(name = "Poverty Rate", 
                       colours = mycolors_True,
                       na.value = "grey") 
```

```{r}
# change two-letter abbreviation to full state name for merging, 'https://rdrr.io/cran/openintro/man/abbr2state.html'
abbr2state <- function(abbr){
  ab    <- tolower(c("AL",
             "AK", "AZ", "KS", "UT", "CO", "CT",
             "DE", "FL", "GA", "HI", "ID", "IL",
             "IN", "IA", "AR", "KY", "LA", "ME",
             "MD", "MA", "MI", "MN", "MS", "MO",
             "MT", "NE", "NV", "NH", "NJ", "NM",
             "NY", "NC", "ND", "OH", "OK", "OR",
             "PA", "RI", "SC", "SD", "TN", "TX",
             "CA", "VT", "VA", "WA", "WV", "WI",
             "WY", "DC"))
  st    <- c("Alabama",
             "Alaska", "Arizona", "Kansas",
             "Utah", "Colorado", "Connecticut",
             "Delaware", "Florida", "Georgia",
             "Hawaii", "Idaho", "Illinois",
             "Indiana", "Iowa", "Arkansas",
             "Kentucky", "Louisiana", "Maine",
             "Maryland", "Massachusetts", "Michigan",
             "Minnesota", "Mississippi", "Missouri",
             "Montana", "Nebraska", "Nevada",
             "New Hampshire", "New Jersey", "New Mexico",
             "New York", "North Carolina", "North Dakota",
             "Ohio", "Oklahoma", "Oregon",
             "Pennsylvania", "Rhode Island", "South Carolina",
             "South Dakota", "Tennessee", "Texas",
             "California", "Vermont", "Virginia",
             "Washington", "West Virginia", "Wisconsin",
             "Wyoming", "District of Columbia")
  st[match(tolower(abbr), ab)]
}

# visualization

# fixed map
merge(map_data("state"), 
                      aggregate(var ~ state, 
                                data = filter(state_data, countystat == "poverty_rate") %>% 
                                  select(year, state, var) %>% 
                                  unique(), 
                                FUN = mean) %>% 
                        mutate(state = abbr2state(state) %>% tolower()), 
                      by.x = 'region', by.y = 'state') %>% 
  ggplot() + 
  geom_polygon(aes(long, lat, 
                   group = group, 
                   fill = var)) + 
  scale_fill_gradientn(colours = mycolors_True, 
                       trans = 'log', 
                       name = 'Variance') + 
  theme_bw() + 
  labs(x = "Longitude", 
       y = "Latitude", 
       title = "Variance of Poverty Rate in Counties, Per State")
```

```{r}
# visualization

merge(map_data("state"), 
                      aggregate(var ~ state, 
                                data = filter(state_data, countystat == "pop_dens") %>% 
                                  select(year, state, var) %>% 
                                  unique(), 
                                FUN = mean) %>% 
                        mutate(state = abbr2state(state) %>% tolower()), 
                      by.x = 'region', by.y = 'state') %>% 
  ggplot() + 
  geom_polygon(aes(long, lat, 
                   group = group, 
                   fill = var)) + 
  scale_fill_gradientn(colours = mycolors_True, 
                       trans = 'log', 
                       name = 'Variance') + 
  theme_bw() + 
  labs(x = "Longitude", 
       y = "Latitude", 
       title = "Variance of Population Density in Counties, Per State")
```

```{r fig.width = 16, fig.height = 6}
aggregate(state_pcrime_rate ~ state, data = state_data, mean) %>% 
  ggplot(aes(x = state, 
             y = state_pcrime_rate, 
             colour = state, 
             group = state)) +
  geom_label(aes(label = state), check_overlap = TRUE)+
  labs(x = "State", 
       y = "Average State Property Crime Rate Per State (including DC)", 
       title = "Average State Property Crime Rate Per State (including DC)")
```

```{r}
df_Farm_Counties <- merge(aggregate(state_p_farm_income ~ state, data = state_data, mean), 
                          aggregate(n_counties ~ state, data = state_data, mean), 
                          by = c('state'))
rownames(df_Farm_Counties) <- df_Farm_Counties$state

set.seed(100)
fit <- kmeans(df_Farm_Counties[, 2:3], 5)
clusplot(df_Farm_Counties, 
         fit$cluster, 
         color = TRUE, 
         shade = TRUE, 
         labels = 2, 
         lines = 0,
         cex = 0.75,
         main = 'K-Means Clustering, Proportion of Farm Income \nand Number of Counties per State')
```

```{r}
df_Farm_Poverty <- merge(aggregate(state_p_farm_income ~ state, data = state_data, mean), 
                         aggregate(state_poverty_rate ~ state, data = state_data, mean), 
                         by = c('state'))
rownames(df_Farm_Poverty) <- df_Farm_Poverty$state

set.seed(100)
fit2 <- kmeans(df_Farm_Poverty[, 2:3], 4)
clusplot(df_Farm_Poverty, 
         fit2$cluster, 
         color = TRUE, 
         shade = TRUE, 
         labels = 2, 
         lines = 0,
         cex = 0.75,
         main = 'K-Means Clustering, Proportion of Farm Income and Poverty Rate')
```

```{r}
df_Crime_Poverty <- merge(aggregate(state_vcrime_rate ~ state, data = state_data, mean), 
                         aggregate(state_poverty_rate ~ state, data = state_data, mean), 
                         by = c('state'))
rownames(df_Crime_Poverty) <- df_Crime_Poverty$state

set.seed(100)
fit2 <- kmeans(df_Crime_Poverty[, 2:3], 4)
clusplot(df_Crime_Poverty, 
         fit2$cluster, 
         color = TRUE, 
         shade = TRUE, 
         labels = 2, 
         lines = 0,
         cex = 0.75,
         main = 'K-Means Clustering, Proportion of Violent Crime Rate and Poverty Rate')
```

```{r}
stopCluster(myCluster)
```
